################################## G3公共地址 ##################################
# SYSTEM
SYSTEM_SPC_VERSION_ADDR = 5
# BMS
BMS_BASE_ADDRESS = 38000
BMS_FAULT_STEP = 200
# PCS
PCS_BASE_ADDRESS = 2600
PCS_FAULT_STEP = 300
PCS_UPGRADE_STATUS_BASE_ADDRESS = PCS_BASE_ADDRESS + 62
PCS_BASE_UPGRADE_PROCESS_ADDR = 2661
PCS_BASE_UPGRADE_STATE_ADDR = 2662
# MV
UPS_BASE_ADDRESS = 27100
MC_BASE_ADDRESS = 27300
MV_FAULT_STEP = 200

# TEST_MODE
TEST_MODE = False


