from constent.bms_fault import BMS_SYSTEM_FAULT_BASE_ADDRESS
from constent.pcs_fault import *
from constent.mv_fault import *

#  =================== 故障/告警寄存器点位列表(bit点位汇总) =================
FAULT_TABLE_ALL = {
    # BMS_FAULT
    BMS_SYSTEM_FAULT_BASE_ADDRESS: {
        0 : "bms.faults.bmsFaultSum.systemWarn",
        1 : "bms.faults.bmsFaultSum.systemAlm",
        2 : "bms.faults.bmsFaultSum.systemCritical",
        3 : "bms.faults.bmsFaultSum.systemForbidChg",
        4 : "bms.faults.bmsFaultSum.systemForbidDischg",
        5 : "bms.faults.bmsFaultSum.pcsControlFault",
        6 : "bms.faults.bmsFaultSum.circuitConectFault",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },

    # PCS_FAULT
    PCS_MS_DSP_FAULT1_BASE_ADDRESS: {
        0 : "alarm.invalid_national_standard",
        1 : "alarm.ac_10min_overvoltage",
        2 : "alarm.ac_level1_overvoltage",
        3 : "alarm.ac_level2_overvoltage",
        4 : "alarm.ac_level3_overvoltage",
        5 : "alarm.ac_level4_overvoltage",
        6 : "alarm.ac_level5_overvoltage",
        7 : "alarm.ac_level1_undervoltage",
        8 : "alarm.ac_level2_undervoltage",
        9 : "alarm.ac_level3_undervoltage",
        10: "alarm.ac_level4_undervoltage",
        11: "alarm.ac_level5_undervoltage",
        12: "alarm.ac_level1_overfrequency",
        13: "alarm.ac_level2_overfrequency",
        14: "alarm.ac_level3_overfrequency",
        15: "alarm.ac_level4_overfrequency"
    },
    PCS_MS_DSP_FAULT2_BASE_ADDRESS: {
        0 : "alarm.ac_level5_overfrequency",
        1 : "alarm.ac_level1_underfrequency",
        2 : "alarm.ac_level2_underfrequency",
        3 : "alarm.ac_level3_underfrequency",
        4 : "alarm.ac_level4_underfrequency",
        5 : "alarm.ac_level5_underfrequency",
        6 : "alarm.freq_change_rate_high",
        7 : "alarm.ac_voltage_unbalance",
        8 : "alarm.ac_instantaneous_overvoltage",
        9 : "alarm.dc_level1_protection",
        10: "alarm.dc_level2_protection",
        11: "alarm.dc_level3_protection",
        12: "alarm.dcv_protection",
        13: "alarm.overmodulation_fault",
        14: "alarm.j1_board_fault",
        15: "alarm.j2_board_fault"
    },
    PCS_MS_DSP_FAULT3_BASE_ADDRESS: {
        0 : "alarm.ac_breaker_fault",
        1 : "alarm.j1_dc_softstart_fault",
        2 : "alarm.j1_dc_precharge_relay_fault",
        3 : "alarm.j1_dc_breaker_fault",
        4 : "alarm.j1_filter_capacitor_breaker_fault",
        5 : "alarm.j2_dc_softstart_fault",
        6 : "alarm.j2_dc_precharge_relay_fault",
        7 : "alarm.j2_dc_breaker_fault",
        8 : "alarm.j2_filter_capacitor_breaker_fault",
        9 : "alarm.ac_sync_fault",
        10: "alarm.emif_write_fault",
        11: "alarm.emif_read_fault",
        12: "alarm.fpga_heartbeat_fault",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_DSP_FAULT4_BASE_ADDRESS: {
        0 : "alarm.ems_comm_loss",
        1 : "alarm.feram_rw_fault",
        2 : "alarm.network_comm_fault",
        3 : "alarm.mv_transformer_fault",
        4 : "alarm.bms_fault",
        5 : "alarm.fpga_comm_fault",
        6 : "alarm.j1_fast_protect_io",
        7 : "alarm.j2_fast_protect_io",
        8 : "alarm.j3_fast_protect_io",
        9 : "alarm.j4_fast_protect_io",
        10: "alarm.io_24v_supply",
        11: "alarm.ctrl_24v_supply",
        12: "alarm.comm_24v_supply",
        13: "alarm.epo",
        14: "alarm.slave_unit_fault",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_FPGA_FAULT1_BASE_ADDRESS: {
        0 : "alarm.j1_fiber_cable_abnormal",
        1 : "alarm.j1_fiber_crc_error",
        2 : "alarm.j2_fiber_cable_abnormal",
        3 : "alarm.j2_fiber_crc_error",
        4 : "alarm.j3_fiber_cable_abnormal",
        5 : "alarm.j3_fiber_crc_error",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_FPGA_FAULT2_BASE_ADDRESS: {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_FPGA_FAULT3_BASE_ADDRESS: {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_FPGA_FAULT4_BASE_ADDRESS: {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_CTR_DSP_FAULT1_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_CTR_DSP_FAULT2_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_SYS_DSP_FAULT1_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_SYS_DSP_FAULT2_BASE_ADDRESS: {
        0 : " alarm.socket_create_fail",
        1 : " alarm.bind_port_fail",
        2 : " alarm.listen_port_fail",
        3 : " alarm.accept_client_fail",
        4 : " alarm.connect_break",
        5 : " alarm.data_send_fail",
        6 : " alarm.data_recv_fail",
        7 : " alarm.data_checksum_error",
        8 : " alarm.comm_timeout",
        9 : " alarm.hardware_fault",
        10: " history.table.pcsGroup.reserved",
        11: " history.table.pcsGroup.reserved",
        12: " history.table.pcsGroup.reserved",
        13: " history.table.pcsGroup.reserved",
        14: " history.table.pcsGroup.reserved",
        15: " history.table.pcsGroup.reserved"
    },
    PCS_ARM_J1DSP_FAULT1_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_J1DSP_FAULT2_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_J2DSP_FAULT1_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_J2DSP_FAULT2_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_PEER_MONITOR_FAULT1_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_PEER_MONITOR_FAULT2_BASE_ADDRESS: {
        0 : "alarm.socket_create_fail",
        1 : "alarm.bind_port_fail",
        2 : "alarm.listen_port_fail",
        3 : "alarm.accept_client_fail",
        4 : "alarm.connect_break",
        5 : "alarm.data_send_fail",
        6 : "alarm.data_recv_fail",
        7 : "alarm.data_checksum_error",
        8 : "alarm.comm_timeout",
        9 : "alarm.hardware_fault",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_ARM_SYS_FAULT_BASE_ADDRESS: {
        0 : "alarm.memory_alloc_fault",
        1 : "alarm.file_open_fault",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_DSP_FAULT1_BASE_ADDRESS: {
        0 : "alarm.ind_inst_overcurrent",
        1 : "alarm.ind_overcurrent",
        2 : "alarm.zero_seq_inst_overcurrent",
        3 : "alarm.zero_seq_overcurrent",
        4 : "alarm.filter_cap_overcurrent",
        5 : "alarm.filter_cap_ac_current",
        6 : "alarm.filter_cap_inst_overcurrent",
        7 : "alarm.batt_inst_overcurrent",
        8 : "alarm.batt_overvoltage",
        9 : "alarm.batt_undervoltage",
        10: "alarm.bus_inst_overvoltage",
        11: "alarm.bus_overvoltage",
        12: "alarm.bus_inst_undervoltage",
        13: "alarm.bus_undervoltage",
        14: "alarm.bus_batt_voltage_diff",
        15: "alarm.bus_inst_mid_offset"
    },
    PCS_DSP_FAULT2_BASE_ADDRESS: {
        0 : "alarm.bus_mid_offset",
        1 : "alarm.batt_reverse_connect",
        2 : "alarm.igbt_overtemp",
        3 : "alarm.ac_cap_overtemp",
        4 : "alarm.dc_cap_overtemp",
        5 : "alarm.dc_fuse_overtemp",
        6 : "alarm.main_fan_undercurrent",
        7 : "alarm.main_fan_overcurrent",
        8 : "alarm.turb_fan_undercurrent",
        9 : "alarm.turb_fan_overcurrent",
        10: "alarm.ac_cap_fan_undercurrent",
        11: "alarm.ac_cap_fan_overcurrent",
        12: "alarm.grid_side_inst_overcurrent",
        13: "alarm.grid_side_overcurrent",
        14: "alarm.internal_amb_overtemp",
        15: "alarm.external_amb_overtemp"
    },
    PCS_DSP_FAULT3_BASE_ADDRESS: {
        0 : "alarm.bus1_insulation_low",
        1 : "alarm.bus2_insulation_low",
        2 : "alarm.dc_fuse_fault",
        3 : "alarm.ac_breaker_trip",
        4 : "alarm.host_status_fb_fault",
        5 : "alarm.reactor_overtemp",
        6 : "alarm.aux_transformer_overtemp",
        7 : "alarm.cabinet_water_ingress",
        8 : "alarm.r_phase_fan_fault",
        9 : "alarm.s_phase_fan_fault",
        10: "alarm.t_phase_fan_fault",
        11: "alarm.io_24v_supply_fault",
        12: "alarm.comm_24v_supply_fault",
        13: "alarm.ctrl_24v_supply_fault",
        14: "alarm.main_fan_supply_fault",
        15: "alarm.emif_write_fault"
    },
    PCS_DSP_FAULT4_BASE_ADDRESS: {
        0 : "alarm.emif_read_fault",
        1 : "alarm.fpga_heartbeat_fault",
        2 : "alarm.network_comm_fault",
        3 : "alarm.imd_comm_fault",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_FPGA_FAULT1_BASE_ADDRESS: {
        0 : "alarm.neg_bus_overvoltage",
        1 : "alarm.pos_bus_overvoltage",
        2 : "alarm.batt_overvoltage",
        3 : "alarm.t_phase_driver_fault",
        4 : "alarm.s_phase_driver_fault",
        5 : "alarm.r_phase_driver_fault",
        6 : "alarm.t_phase_wave_lim_fault",
        7 : "alarm.s_phase_wave_lim_fault",
        8 : "alarm.r_phase_wave_lim_fault",
        9 : "alarm.batt_overcurrent",
        10: "alarm.t_phase_overcurrent",
        11: "alarm.s_phase_overcurrent",
        12: "alarm.r_phase_overcurrent",
        13: "alarm.r_phase_overcurrent",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_FPGA_FAULT2_BASE_ADDRESS: {
        0 : "alarm.tube1_up_short",
        1 : "alarm.tube1_up_undervoltage",
        2 : "alarm.tube2_down_short",
        3 : "alarm.tube2_down_undervoltage",
        4 : "alarm.tube3_short",
        5 : "alarm.tube3_undervoltage",
        6 : "alarm.tube4_short",
        7 : "alarm.tube4_undervoltage",
        8 : "alarm.tube5_short",
        9 : "alarm.tube5_undervoltage",
        10: "alarm.tube6_short",
        11: "alarm.tube6_undervoltage",
        12: "alarm.upper_gate_detect",
        13: "alarm.lower_gate_detect",
        14: "alarm.reactor_overtemp",
        15: "alarm.narrow_pulse"
    },
    PCS_FPGA_FAULT3_BASE_ADDRESS: {
        0 : "alarm.tube1_up_short",
        1 : "alarm.tube1_up_undervoltage",
        2 : "alarm.tube2_down_short",
        3 : "alarm.tube2_down_undervoltage",
        4 : "alarm.tube3_short",
        5 : "alarm.tube3_undervoltage",
        6 : "alarm.tube4_short",
        7 : "alarm.tube4_undervoltage",
        8 : "alarm.tube5_short",
        9 : "alarm.tube5_undervoltage",
        10: "alarm.tube6_short",
        11: "alarm.tube6_undervoltage",
        12: "alarm.upper_gate_detect",
        13: "alarm.lower_gate_detect",
        14: "alarm.reactor_overtemp",
        15: "alarm.narrow_pulse"
    },
    PCS_FPGA_FAULT4_BASE_ADDRESS: {
        0 : "alarm.tube1_up_short",
        1 : "alarm.tube1_up_undervoltage",
        2 : "alarm.tube2_down_short",
        3 : "alarm.tube2_down_undervoltage",
        4 : "alarm.tube3_short",
        5 : "alarm.tube3_undervoltage",
        6 : "alarm.tube4_short",
        7 : "alarm.tube4_undervoltage",
        8 : "alarm.tube5_short",
        9 : "alarm.tube5_undervoltage",
        10: "alarm.tube6_short",
        11: "alarm.tube6_undervoltage",
        12: "alarm.upper_gate_detect",
        13: "alarm.lower_gate_detect",
        14: "alarm.reactor_overtemp",
        15: "alarm.narrow_pulse"
    },
    PCS_FPGA2_FAULT1_BASE_ADDRESS: {
        0 : "alarm.fiber_cable_abnormal",
        1 : "alarm.j1_fiber_crc_error",
        2 : "alarm.r_phase_drive_abnormal",
        3 : "alarm.s_phase_drive_abnormal",
        4 : "alarm.t_phase_drive_abnormal",
        5 : "alarm.r_phase_ntc_abnormal",
        6 : "alarm.s_phase_ntc_abnormal",
        7 : "alarm.t_phase_ntc_abnormal",
        8 : "alarm.fiber_fast_protect",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_FPGA2_FAULT2_BASE_ADDRESS: {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_FPGA2_FAULT3_BASE_ADDRESS: {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_FPGA2_FAULT4_BASE_ADDRESS: {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },

    # PCS_WARNING
    PCS_MS_DSP_WARNING1_BASE_ADDRESS:{
        0 : "alarm.network_communication_lost",
        1 : "alarm.smoke_detector_alarm",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_DSP_WARNING2_BASE_ADDRESS:{
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_DSP_WARNING3_BASE_ADDRESS:{
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_MS_DSP_WARNING4_BASE_ADDRESS:{
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_DSP_WARNING1_BASE_ADDRESS:{
        0 : "alarm.j_board_fpga_alarm",
        1 : "alarm.humidity_high_alarm",
        2 : "alarm.dehumidifier_fault_alarm",
        3 : "alarm.ups_undervoltage",
        4 : "alarm.ups_fault",
        5 : "alarm.j_board_overtemp",
        6 : "alarm.ups_ac_input_lost",
        7 : "alarm.dc_spd_alarm",
        8 : "alarm.ac_spd_alarm",
        9 : "alarm.aux_transformer_spd_alarm",
        10: "alarm.emif_read_write_alarm",
        11: "alarm.network_communication_lost",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_DSP_WARNING2_BASE_ADDRESS:{
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_DSP_WARNING3_BASE_ADDRESS:{
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_DSP_WARNING4_BASE_ADDRESS:{
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    PCS_FPGA_WARNING1_BASE_ADDRESS:{        
        0 : "alarm.fiber_cable_abnormal_alarm",
        1 : "alarm.fiber_crc_error_alarm",
        2 : "alarm.r_phase_drive_decode_alarm",
        3 : "alarm.s_phase_drive_decode_alarm",
        4 : "alarm.t_phase_drive_decode_alarm",
        5 : "alarm.r_phase_ntc_sample_alarm",
        6 : "alarm.s_phase_ntc_sample_alarm",
        7 : "alarm.t_phase_ntc_sample_alarm",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"},
    PCS_FPGA_WARNING2_BASE_ADDRESS:{        
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"},
    PCS_FPGA_WARNING3_BASE_ADDRESS:{        
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"},
    PCS_FPGA_WARNING4_BASE_ADDRESS:{        
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"},

    # MV
    MV_UPS_ALARM1_BASE_ADDRESS      : {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "mv.ups.upsWarn1.chargerFail",
        3 : "alarm.reactor_overtemp",
        4 : "history.table.pcsGroup.reserved",
        5 : "mv.ups.upsWarn1.epoActive",
        6 : "history.table.pcsGroup.reserved",
        7 : "mv.ups.upsWarn1.overloadWarning",
        8 : "mv.ups.upsWarn1.batteryLow",
        9 : "mv.ups.upsWarn1.batteryOvercharge",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "mv.ups.upsWarn1.batteryOpen"
    },
    MV_UPS_ALARM2_BASE_ADDRESS      : {
        0 : "history.table.pcsGroup.reserved",
        1 : "history.table.pcsGroup.reserved",
        2 : "mv.ups.upsWarn2.EEPROMOperationError",
        3 : "history.table.pcsGroup.reserved",
        4 : "history.table.pcsGroup.reserved",
        5 : "history.table.pcsGroup.reserved",
        6 : "history.table.pcsGroup.reserved",
        7 : "history.table.pcsGroup.reserved",
        8 : "mv.ups.upsWarn2.WarningForBatteryReplace",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "history.table.pcsGroup.reserved",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "history.table.pcsGroup.reserved"
    },
    MV_UPS_ALARM3_BASE_ADDRESS      : {
        0 : "history.table.pcsGroup.reserved",
        1 : "mv.ups.upsWarn3.upsBypassInternalFault",
        2 : "history.table.pcsGroup.reserved",
        3 : "mv.ups.upsWarn3.upsBypassUpsLinkKeyCommand",
        4 : "mv.ups.upsWarn3.upsReturnFromBypass",
        5 : "history.table.pcsGroup.reserved",
        6 : "mv.ups.upsWarn3.upsReadyPowerLoadReturnNormalVoltage",
        7 : "mv.ups.upsWarn3.upsReadyPowerLoadReturnNormalVoltage",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "mv.ups.upsWarn3.onlineMode",
        12: "mv.ups.upsModeDes.batteryMode",
        13: "mv.ups.upsWarn3.overloadOutput",
        14: "mv.ups.upsWarn1.batteryLow",
        15: "history.table.pcsGroup.reserved"
    },
    MV_UPS_ALARM4_BASE_ADDRESS      : {
        0 : "mv.ups.upsWarn4.upsOutputUnpoweredLowBattery",
        1 : "history.table.pcsGroup.reserved",
        2 : "history.table.pcsGroup.reserved",
        3 : "mv.ups.upsWarn4.upsSleepModeAtDDDCommand",
        4 : "mv.ups.upsWarn4.upsShutdownModeSCommand",
        5 : "mv.ups.upsWarn4.batteryChargerFailure",
        6 : "history.table.pcsGroup.reserved",
        7 : "mv.ups.upsWarn4.internalTempExceedNominalLimits",
        8 : "history.table.pcsGroup.reserved",
        9 : "history.table.pcsGroup.reserved",
        10: "history.table.pcsGroup.reserved",
        11: "history.table.pcsGroup.reserved",
        12: "mv.ups.upsWarn4.upsFaultDcImbalanceBypass",
        13: "history.table.pcsGroup.reserved",
        14: "history.table.pcsGroup.reserved",
        15: "mv.ups.upsWarn4.badOutputVoltage"
    },
    MV_MC_Trip_Summary_ADDRESS      : "mv.measure.tripSummaryTotal",
    MV_MC_Alarm_Summary_ADDRESS     : "mv.measure.alarmSummaryTotal",
    MV_MC_Real_time_Trip_ADDRESS    : "mv.measure.realTimeTripTotal",
    MV_MC_Real_time_Alarm_ADDRESS   : "mv.measure.realTimeAlarmTotal",
    MV_MC_Device_Fault_ADDRESS      : "mv.measure.deviceFaultTotal",
    MV_MC_PCS_FAULT1_BASE_ADDRESS   : "mv.measure.pcs1FaultSignal",
    MV_MC_PCS_FAULT2_BASE_ADDRESS   : "mv.measure.pcs2FaultSignal",
    MV_MC_PCS_FAULT3_BASE_ADDRESS   : "mv.measure.pcs3FaultSignal",
    MV_MC_PCS_FAULT4_BASE_ADDRESS   : "mv.measure.pcs4FaultSignal"
}
