from constent.common import PCS_BASE_ADDRESS

################################# PCS 故障寄存器地址 ##################################
# PCS故障寄存器地址,共31个寄存器,4个分区
# MS控制DSP故障信息寄存器
PCS_MS_DSP_FAULT1_OFFSET = 23
PCS_MS_DSP_FAULT2_OFFSET = 24
PCS_MS_DSP_FAULT3_OFFSET = 25
PCS_MS_DSP_FAULT4_OFFSET = 26
PCS_MS_DSP_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_FAULT1_OFFSET
PCS_MS_DSP_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_FAULT2_OFFSET
PCS_MS_DSP_FAULT3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_FAULT3_OFFSET
PCS_MS_DSP_FAULT4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_FAULT4_OFFSET

# MS控制FPGA故障信息寄存器
PCS_MS_FPGA_FAULT1_OFFSET = 31
PCS_MS_FPGA_FAULT2_OFFSET = 32
PCS_MS_FPGA_FAULT3_OFFSET = 33
PCS_MS_FPGA_FAULT4_OFFSET = 34
PCS_MS_FPGA_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_FAULT1_OFFSET
PCS_MS_FPGA_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_FAULT2_OFFSET
PCS_MS_FPGA_FAULT3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_FAULT3_OFFSET
PCS_MS_FPGA_FAULT4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_FAULT4_OFFSET

# ARM与控制DSP间通讯故障信息寄存器
PCS_ARM_CTR_DSP_FAULT1_OFFSET = 50
PCS_ARM_CTR_DSP_FAULT2_OFFSET = 51
PCS_ARM_CTR_DSP_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_CTR_DSP_FAULT1_OFFSET
PCS_ARM_CTR_DSP_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_CTR_DSP_FAULT2_OFFSET

#ARM与系统DSP间通讯故障信息寄存器
PCS_ARM_SYS_DSP_FAULT1_OFFSET = 52
PCS_ARM_SYS_DSP_FAULT2_OFFSET = 53
PCS_ARM_SYS_DSP_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_SYS_DSP_FAULT1_OFFSET
PCS_ARM_SYS_DSP_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_SYS_DSP_FAULT2_OFFSET

# ARM与J1DSP间通讯故障信息寄存器
PCS_ARM_J1DSP_FAULT1_OFFSET = 54
PCS_ARM_J1DSP_FAULT2_OFFSET = 55
PCS_ARM_J1DSP_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_J1DSP_FAULT1_OFFSET
PCS_ARM_J1DSP_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_J1DSP_FAULT2_OFFSET

# ARM与J2DSP间通讯故障信息寄存器
PCS_ARM_J2DSP_FAULT1_OFFSET = 56
PCS_ARM_J2DSP_FAULT2_OFFSET = 57
PCS_ARM_J2DSP_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_J2DSP_FAULT1_OFFSET
PCS_ARM_J2DSP_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_J2DSP_FAULT2_OFFSET

# ARM与对端监控板间通讯故障信息寄存器
PCS_ARM_PEER_MONITOR_FAULT1_OFFSET = 58
PCS_ARM_PEER_MONITOR_FAULT2_OFFSET = 59
PCS_ARM_PEER_MONITOR_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_PEER_MONITOR_FAULT1_OFFSET
PCS_ARM_PEER_MONITOR_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_PEER_MONITOR_FAULT2_OFFSET

# ARM系统级故障(内存、文件、设备)
PCS_ARM_SYS_FAULT_OFFSET = 60
PCS_ARM_SYS_FAULT_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_ARM_SYS_FAULT_OFFSET

# DSP故障信息寄存器
PCS_DSP_FAULT1_OFFSET = 152
PCS_DSP_FAULT2_OFFSET = 153
PCS_DSP_FAULT3_OFFSET = 154
PCS_DSP_FAULT4_OFFSET = 155
PCS_DSP_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_FAULT1_OFFSET
PCS_DSP_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_FAULT2_OFFSET
PCS_DSP_FAULT3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_FAULT3_OFFSET
PCS_DSP_FAULT4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_FAULT4_OFFSET

# FPGA故障信息寄存器
PCS_FPGA_FAULT1_OFFSET = 156
PCS_FPGA_FAULT2_OFFSET = 157
PCS_FPGA_FAULT3_OFFSET = 158
PCS_FPGA_FAULT4_OFFSET = 159
PCS_FPGA_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_FAULT1_OFFSET
PCS_FPGA_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_FAULT2_OFFSET
PCS_FPGA_FAULT3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_FAULT3_OFFSET
PCS_FPGA_FAULT4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_FAULT4_OFFSET

# FPGA2故障信息寄存器
PCS_FPGA2_FAULT1_OFFSET = 160
PCS_FPGA2_FAULT2_OFFSET = 161
PCS_FPGA2_FAULT3_OFFSET = 162
PCS_FPGA2_FAULT4_OFFSET = 163
PCS_FPGA2_FAULT1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA2_FAULT1_OFFSET
PCS_FPGA2_FAULT2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA2_FAULT2_OFFSET
PCS_FPGA2_FAULT3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA2_FAULT3_OFFSET
PCS_FPGA2_FAULT4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA2_FAULT4_OFFSET

# PCS告警寄存器地址
# MS控制DSP告警信息寄存器
PCS_MS_DSP_WARNING1_OFFSET = 27
PCS_MS_DSP_WARNING2_OFFSET = 28
PCS_MS_DSP_WARNING3_OFFSET = 29
PCS_MS_DSP_WARNING4_OFFSET = 30
PCS_MS_DSP_WARNING1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_WARNING1_OFFSET
PCS_MS_DSP_WARNING2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_WARNING2_OFFSET
PCS_MS_DSP_WARNING3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_WARNING3_OFFSET
PCS_MS_DSP_WARNING4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_DSP_WARNING4_OFFSET

# MS控制FPGA告警信息寄存器,无点位定义
# PCS_MS_FPGA_WARNING1_OFFSET = 35
# PCS_MS_FPGA_WARNING2_OFFSET = 36
# PCS_MS_FPGA_WARNING3_OFFSET = 37
# PCS_MS_FPGA_WARNING4_OFFSET = 38
# PCS_MS_FPGA_WARNING1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_WARNING1_OFFSET
# PCS_MS_FPGA_WARNING2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_WARNING2_OFFSET
# PCS_MS_FPGA_WARNING3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_WARNING3_OFFSET
# PCS_MS_FPGA_WARNING4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_MS_FPGA_WARNING4_OFFSET

# DSP告警信息寄存器
PCS_DSP_WARNING1_OFFSET = 164
PCS_DSP_WARNING2_OFFSET = 165
PCS_DSP_WARNING3_OFFSET = 166
PCS_DSP_WARNING4_OFFSET = 167
PCS_DSP_WARNING1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_WARNING1_OFFSET
PCS_DSP_WARNING2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_WARNING2_OFFSET
PCS_DSP_WARNING3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_WARNING3_OFFSET
PCS_DSP_WARNING4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_DSP_WARNING4_OFFSET

# FPGA告警信息寄存器
PCS_FPGA_WARNING1_OFFSET = 168
PCS_FPGA_WARNING2_OFFSET = 169
PCS_FPGA_WARNING3_OFFSET = 170
PCS_FPGA_WARNING4_OFFSET = 171
PCS_FPGA_WARNING1_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_WARNING1_OFFSET
PCS_FPGA_WARNING2_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_WARNING2_OFFSET
PCS_FPGA_WARNING3_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_WARNING3_OFFSET
PCS_FPGA_WARNING4_BASE_ADDRESS = PCS_BASE_ADDRESS + PCS_FPGA_WARNING4_OFFSET

# PCS故障信息寄存器地址
PCS_FAULT_ADDR_LIST = [
    PCS_MS_DSP_FAULT1_BASE_ADDRESS,
    PCS_MS_DSP_FAULT2_BASE_ADDRESS,
    PCS_MS_DSP_FAULT3_BASE_ADDRESS,
    PCS_MS_DSP_FAULT4_BASE_ADDRESS,
    PCS_MS_FPGA_FAULT1_BASE_ADDRESS,
    PCS_MS_FPGA_FAULT2_BASE_ADDRESS,
    PCS_MS_FPGA_FAULT3_BASE_ADDRESS,
    PCS_MS_FPGA_FAULT4_BASE_ADDRESS,
    PCS_ARM_CTR_DSP_FAULT1_BASE_ADDRESS,
    PCS_ARM_CTR_DSP_FAULT2_BASE_ADDRESS,
    PCS_ARM_SYS_DSP_FAULT1_BASE_ADDRESS,
    PCS_ARM_SYS_DSP_FAULT2_BASE_ADDRESS,
    PCS_ARM_J1DSP_FAULT1_BASE_ADDRESS,
    PCS_ARM_J1DSP_FAULT2_BASE_ADDRESS,
    PCS_ARM_J2DSP_FAULT1_BASE_ADDRESS,
    PCS_ARM_J2DSP_FAULT2_BASE_ADDRESS,
    PCS_ARM_PEER_MONITOR_FAULT1_BASE_ADDRESS,
    PCS_ARM_PEER_MONITOR_FAULT2_BASE_ADDRESS,
    PCS_ARM_SYS_FAULT_BASE_ADDRESS,
    PCS_DSP_FAULT1_BASE_ADDRESS,
    PCS_DSP_FAULT2_BASE_ADDRESS,
    PCS_DSP_FAULT3_BASE_ADDRESS,
    PCS_DSP_FAULT4_BASE_ADDRESS,
    PCS_FPGA_FAULT1_BASE_ADDRESS,
    PCS_FPGA_FAULT2_BASE_ADDRESS,
    PCS_FPGA_FAULT3_BASE_ADDRESS,
    PCS_FPGA_FAULT4_BASE_ADDRESS,
    PCS_FPGA2_FAULT1_BASE_ADDRESS,
    PCS_FPGA2_FAULT2_BASE_ADDRESS,
    PCS_FPGA2_FAULT3_BASE_ADDRESS,
    PCS_FPGA2_FAULT4_BASE_ADDRESS,
]

# PCS告警信息寄存器地址
PCS_WARNING_ADDR_LIST = [
    PCS_MS_DSP_WARNING1_BASE_ADDRESS,
    PCS_MS_DSP_WARNING2_BASE_ADDRESS,
    PCS_MS_DSP_WARNING3_BASE_ADDRESS,
    PCS_MS_DSP_WARNING4_BASE_ADDRESS,
    # PCS_MS_FPGA_WARNING1_BASE_ADDRESS,
    # PCS_MS_FPGA_WARNING2_BASE_ADDRESS,
    # PCS_MS_FPGA_WARNING3_BASE_ADDRESS,
    # PCS_MS_FPGA_WARNING4_BASE_ADDRESS,
    PCS_DSP_WARNING1_BASE_ADDRESS,
    PCS_DSP_WARNING2_BASE_ADDRESS,
    PCS_DSP_WARNING3_BASE_ADDRESS,
    PCS_DSP_WARNING4_BASE_ADDRESS,
    PCS_FPGA_WARNING1_BASE_ADDRESS,
    PCS_FPGA_WARNING2_BASE_ADDRESS,
    PCS_FPGA_WARNING3_BASE_ADDRESS,
    PCS_FPGA_WARNING4_BASE_ADDRESS
]

# PCS检查地址列表
PCS_CHECK_ADDR_LIST = {
    "fault": PCS_FAULT_ADDR_LIST,
    "warning": PCS_WARNING_ADDR_LIST
}
