from constent.common import UPS_BASE_ADDRESS, MC_BASE_ADDRESS

################################# MV 故障寄存器地址 ##################################
# MV历史故障数据地址,共31个寄存器,4个分区,起始地址UPS_BASE_ADDRESS,MC_BASE_ADDRESS
# UPS
MV_UPS_ALARM1_OFFSET_ADDRESS = 29
MV_UPS_ALARM2_OFFSET_ADDRESS = 30
MV_UPS_ALARM3_OFFSET_ADDRESS = 31
MV_UPS_ALARM4_OFFSET_ADDRESS = 32
MV_UPS_ALARM1_BASE_ADDRESS = UPS_BASE_ADDRESS + MV_UPS_ALARM1_OFFSET_ADDRESS
MV_UPS_ALARM2_BASE_ADDRESS = UPS_BASE_ADDRESS + MV_UPS_ALARM2_OFFSET_ADDRESS
MV_UPS_ALARM3_BASE_ADDRESS = UPS_BASE_ADDRESS + MV_UPS_ALARM3_OFFSET_ADDRESS
MV_UPS_ALARM4_BASE_ADDRESS = UPS_BASE_ADDRESS + MV_UPS_ALARM4_OFFSET_ADDRESS
# MC
MV_MC_Trip_Summary_OFFSET_ADDRESS = 0
MV_MC_Alarm_Summary_OFFSET_ADDRESS = 1
MV_MC_Real_time_Trip_OFFSET_ADDRESS = 2
MV_MC_Real_time_Alarm_OFFSET_ADDRESS = 3
MV_MC_Device_Fault_OFFSET_ADDRESS = 4
MV_MC_Trip_Summary_ADDRESS = MC_BASE_ADDRESS + MV_MC_Trip_Summary_OFFSET_ADDRESS
MV_MC_Alarm_Summary_ADDRESS = MC_BASE_ADDRESS + MV_MC_Alarm_Summary_OFFSET_ADDRESS
MV_MC_Real_time_Trip_ADDRESS = MC_BASE_ADDRESS + MV_MC_Real_time_Trip_OFFSET_ADDRESS
MV_MC_Real_time_Alarm_ADDRESS = MC_BASE_ADDRESS + MV_MC_Real_time_Alarm_OFFSET_ADDRESS
MV_MC_Device_Fault_ADDRESS = MC_BASE_ADDRESS + MV_MC_Device_Fault_OFFSET_ADDRESS

MV_MC_PCS_FAULT1_OFFSET_ADDRESS = 55
MV_MC_PCS_FAULT2_OFFSET_ADDRESS = 56
MV_MC_PCS_FAULT3_OFFSET_ADDRESS = 57
MV_MC_PCS_FAULT4_OFFSET_ADDRESS = 58
MV_MC_PCS_FAULT1_BASE_ADDRESS = MC_BASE_ADDRESS + MV_MC_PCS_FAULT1_OFFSET_ADDRESS
MV_MC_PCS_FAULT2_BASE_ADDRESS = MC_BASE_ADDRESS + MV_MC_PCS_FAULT2_OFFSET_ADDRESS
MV_MC_PCS_FAULT3_BASE_ADDRESS = MC_BASE_ADDRESS + MV_MC_PCS_FAULT3_OFFSET_ADDRESS
MV_MC_PCS_FAULT4_BASE_ADDRESS = MC_BASE_ADDRESS + MV_MC_PCS_FAULT4_OFFSET_ADDRESS

MV_FAULT_ADDR_LIST = [
    MV_UPS_ALARM1_BASE_ADDRESS,
    MV_UPS_ALARM2_BASE_ADDRESS,
    MV_UPS_ALARM3_BASE_ADDRESS,
    MV_UPS_ALARM4_BASE_ADDRESS,
    MV_MC_Trip_Summary_ADDRESS,
    MV_MC_Alarm_Summary_ADDRESS,
    MV_MC_Real_time_Trip_ADDRESS,
    MV_MC_Real_time_Alarm_ADDRESS,
    MV_MC_Device_Fault_ADDRESS,
    MV_MC_PCS_FAULT1_BASE_ADDRESS,
    MV_MC_PCS_FAULT2_BASE_ADDRESS,
    MV_MC_PCS_FAULT3_BASE_ADDRESS,
    MV_MC_PCS_FAULT4_BASE_ADDRESS
]